alias gs="git status"
alias gc="git commit"
alias gca="git add -A && git commit"
alias gd="git diff"
alias gl="git log"
alias gp="git pull"
alias gcb="git checkout -b"
alias gco="git checkout"
alias gf="git fetch"
alias gm="git merge"

alias ls="ls --color"
alias ll="ls --color -lAh"

alias top="btm -b"
alias py="python3"
alias bye="doas shutdown -P now"
