[[language]]
name = "latex"

[language-server.texlab.config.texlab]
auxDirectory = "build"

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.build]
forwardSearchAfter = true
onSave = true
executable = "tectonic"
args = [ "%f", "--outdir=build" ]

[[language]]
name = "c"
indent = { tab-width = 8, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "gas"
language-servers = [ "asm-lsp" ]

[language-server.asm-lsp]
command = "asm-lsp"
