default_font: &default_font ZedMono NFM Medium:pixelsize=38
icons_font: &icons_font ZedMono NF:pixelsize=38

bar:
  height: 50
  location: top
  font: *default_font
  left-margin: 10
  right-margin: 10

  foreground: 3c3836ff
  background: fbf1c7ff

  border:
    width: 6
    color: 3c3836ff
    left-margin: 300
    right-margin: 300
    top-margin: 30

  left:
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{linear_volume}%", foreground: 9d0006ff, right-margin: 15}}
              ~muted: {string: {text: "{linear_volume}%", right-margin: 15}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "󰋋", font: *icons_font}
                        default:
                          - ramp:
                              tag: linear_volume
                              items:
                                - string: {text: "󰕿", font: *icons_font, right-margin: 15}
                                - string: {text: "󰖀", font: *icons_font, right-margin: 15}
                                - string: {text: "󰕾", font: *icons_font, right-margin: 15}
                    type == "source":
                      - string: {text: "󰍬", font: *icons_font, right-margin: 8}
              - map:
                  <<: *volume
  center:
    - clock:
        date-format: "%A [%D]"
        time-format: "%H:%M:%S"
        content:
          - string: {text: "{date}", right-margin: 14}
          - string: {text: "{time}"}

  right:
    - backlight:
        name: amdgpu_bl0
        content: [ string: {text: 󰌵, font: *icons_font, right-margin: 8}, string: {text: "{percent}%", right-margin: 15}]

    - battery:
        name: BAT0
        poll-interval: 10000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                      - string: {text: , font: *icons_font, right-margin: 23}
                - string: {text: "{capacity}%"}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 79740eff, right-margin: 8}
                - string: {text: "{capacity}%"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: 9d0006ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: 9d0006ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: 9d0006ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: b57614ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: b57614ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: b57614ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: b57614ff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: 79740eff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: 79740eff, font: *icons_font, right-margin: 15}
                      - string: {text:  , foreground: 79740eff, font: *icons_font, right-margin: 15}
                - string: {text: "{capacity}%"}
