[[language]]
name = "latex"

[language-server.texlab.config.texlab]
auxDirectory = "build"

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.build]
forwardSearchAfter = true
onSave = true
executable = "tectonic"
args = [ "%f", "--outdir=build" ]

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "clangd" ]
file-types = [ "c", "h" ]
formatter = { command = "clang-format" }

[[language]]
name = "rust"
auto-format = false
