#!/usr/bin/env sh



# {{ GLOBALS }}
riverctl set-repeat 50 300
riverctl rule-add -app-id "bar" csd
riverctl keyboard-layout -options grp:alt_shift_toggle us,ru
# {{ GLOBALS }}



# {{ APPS }}
riverctl map normal Super Return spawn "kitty"
riverctl map normal Super B spawn "firefox --profile ~/.config/firefox"
riverctl map normal Super Z spawn "zathura"
riverctl map normal Super T spawn "telegram-desktop"
riverctl map normal Super P spawn "shotman --copy --capture region"
# {{ APPS }}



# {{ ROOT }}
riverctl map normal Super+Shift Q exit
riverctl map normal Super+Shift R spawn riverctl
# {{ ROOT }}



# {{ TOUCHPAD }}
riverctl input pointer-1739-52981-SYNA0A00:00_06CB:CEF5_Touchpad disable-while-typing enabled
riverctl input pointer-1739-52981-SYNA0A00:00_06CB:CEF5_Touchpad middle-emulation enabled
riverctl input pointer-1739-52981-SYNA0A00:00_06CB:CEF5_Touchpad scroll-method two-finger
riverctl input pointer-1739-52981-SYNA0A00:00_06CB:CEF5_Touchpad natural-scroll enabled
riverctl input pointer-1739-52981-SYNA0A00:00_06CB:CEF5_Touchpad tap enabled

riverctl hide-cursor when-typing enabled
riverctl focus-follows-cursor normal
# {{ TOUCHPAD }}



# {{ THEME }}
riverctl border-width 3
riverctl border-color-focused 0xd65d0e
riverctl border-color-unfocused 0xebdbb2
# {{ THEME }}



# {{ LAYOUT }}
riverctl default-layout rivertile

rivertile spawn "-view-padding 6 -outer-padding 6"
# {{ LAYOUT }}



# {{ BINDINGS }}
riverctl map normal Super W close
riverctl map normal Super F toggle-float
riverctl map normal Super S toggle-fullscreen

riverctl map normal Super H move left 100
riverctl map normal Super J move down 100
riverctl map normal Super K move up 100
riverctl map normal Super L move right 100

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
done

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"
    riverctl map $mode None XF86AudioLowerVolume  spawn "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%-"
    riverctl map $mode None XF86AudioMute         spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

    riverctl map $mode None XF86MonBrightnessUp   spawn "brightnessctl set 5%+"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"
done
# {{ BINDINGS }}



# {{ AUTOSTART }}
riverctl spawn "mako"
riverctl spawn "pipewire"
riverctl spawn "pipewire-pulse"
riverctl spawn "wbg ~/.config/bg/bg.jpg"
riverctl spawn "wlr-randr --output eDP-1 --custom-mode 2880x1800@120Hz --scale 1.5"
riverctl spawn "waybar"
riverctl spawn "kitty"
# {{ AUTOSTART }}
